// Added by AlbertoSc16: Definition of endpoints (GET, POST, PUT, PATCH, DELETE)

const express = require("express");
const router = express.Router();
const { validationResult } = require("express-validator");

const studentController = require("../controllers/studentController");
const {
  createStudentValidators,
  updateStudentValidators,
  patchStudentValidators,
  listStudentsValidators,
  idOnlyValidators,
} = require("../utils/validators");

// --- Middleware: centralized handling of validation errors ---

/*
 * handleValidationErrors
 * Intercepts errors generated by express-validator and responds with 422
 * if there is a problem, preventing invalid data from reaching the controller.
 */
const handleValidationErrors = (req, res, next) => {
  const errors = validationResult(req);
  if (!errors.isEmpty()) {
    return res.status(422).json({
      success: false,
      message: "Validation error in the data sent.",
      errors: errors.array().map((err) => ({
        field: err.path || err.param,
        message: err.msg,
        value: err.value,
      })),
    });
  }
  next();
};

// --- Student routes ---

/**
 * GET /api/students
 * Gets the list of all students with support for:
 *   - Filters: major, semester, is_active
 *   - Pagination: page, limit
 */
router.get(
  "/students",
  listStudentsValidators,
  handleValidationErrors,
  studentController.getAllStudents
);

/**
 * GET /api/students/:id
 * Retrieves a specific student by their ID.
 * Responds with a 404 if they do not exist.
 */
router.get(
  "/students/:id",
  idOnlyValidators,
  handleValidationErrors,
  studentController.getStudentById
);

/**
 * POST /api/students
 * Create a new student.
 * Required body: first_name, last_name, email, major, semester,
 *                 enrollment_date (+ optional: gpa, phone_number, is_active)
 * Respond with 201 and the created student.
 */
router.post(
  "/students",
  createStudentValidators,
  handleValidationErrors,
  studentController.createStudent
);

/**
 * PUT /api/students/:id
 * Completely replaces a student's information.
 * All required fields must be in the body.
 * Responds with a 404 if the student does not exist.
 */
router.put(
  "/students/:id",
  updateStudentValidators,
  handleValidationErrors,
  studentController.updateStudent
);

/**
 * PATCH /api/students/:id
 * Partially updates a student (only the fields sent).
 * Responds with 404 if the student does not exist.
 */
router.patch(
  "/students/:id",
  patchStudentValidators,
  handleValidationErrors,
  studentController.patchStudent
);

/**
 * DELETE /api/students/:id
 * Soft delete: marks the student as inactive (is_active = false).
 * Responds with 200 with confirmation or 404 if it does not exist.
 */
router.delete(
  "/students/:id",
  idOnlyValidators,
  handleValidationErrors,
  studentController.deleteStudent
);

module.exports = router;